service: node-dns

custom:
  HOST_ZONE_ID: Z2KXYONGFSRPE1 # change this with your hosted zone resource record

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  memorySize: 128 # memory limit for all functions
  environment:
    BASE_DOMAIN: inexortestnetwork.tk # change this with the domain your hosted zone is designated for
    HOST_ZONE_ID: ${self:custom.HOST_ZONE_ID}
    ALIAS_FILE: https://gist.githubusercontent.com/Fohlen/9a0f106ab12a0cc4202ed87c6b18fae6/raw/fdd085dd799a137e7c4f6f92f9b2474801da27da/alias-test.json # change this to the aliases JSON
  resources:
    Resources:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: nodes
        AttributeDefinitions:
          - AttributeName: node
            KeyType: S
        KeySchema:
          - AttributeName: node
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "Route53:ChangeResourceRecordSets"
      Resource:
        - "arn:aws:route53:::hostedzone/${self:custom.HOST_ZONE_ID}"
    - Effect: "Allow"
      Action:
        - "DynamoDB:GetItem"
        - "DynamoDB:PutItem"
        - "DynamoDB:UpdateItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/nodes"

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: put
  revoke:
    handler: handler.revoke
    events:
      - http:
          path: revoke
          method: delete
  aliases:
    handler: handler.update_aliases
    events:
      - schedule: rate(2 hours)
