service: node-dns

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  environment:
    BASE_DOMAIN: inexortestnetwork.tk
    HOST_ZONE_ID: Z2KXYONGFSRPE1
    ALIAS_FILE: https://gist.githubusercontent.com/Fohlen/9a0f106ab12a0cc4202ed87c6b18fae6/raw/fdd085dd799a137e7c4f6f92f9b2474801da27da/alias-test.json

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: put
  revoke:
    handler: handler.revoke
    events:
      - http:
          path: revoke
          method: delete
  aliases:
    handler: handler.update_aliases
    events:
      - schedule: rate(2 hours)
