service: node-dns

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  register:
    handler: handler.register
    events:
      - http:
        path: register
        method: get
  revoke:
    handler: handler.revoke
      - http:
        path: revoke
        method: delete
  aliases:
    handler: handler.update_aliases
      - schedule: rate(2 hours)

environment:
  BASE_DOMAIN: node.inexor.network
  HOST_ZONE_ID: someid
  ALIAS_FILE: https://raw.githubusercontent.com/inexorgame/blog-data/config/alias.json

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
