service: node-dns

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

environment:
  BASE_DOMAIN: node.inexor.network
  HOST_ZONE_ID: someid
  ALIAS_FILE: https://raw.githubusercontent.com/inexorgame/blog-data/config/alias.json


functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: get
  revoke:
    handler: handler.revoke
    events:
      - http:
          path: revoke
          method: delete
  aliases:
    handler: handler.update_aliases
    events:
      - schedule: rate(2 hours)
